import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Button, Header, Card } from "@subzero/glacier";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <Header />
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a> with Subzero
      </h1>

      <p className={styles.description}>
        <Button color="primary" size="medium" variant="text">
          Start Hacking
        </Button>
      </p>

      <div className={styles.welcome}>
        <a href="https://subzero.staging.axisb.com/">
          <Card
            assets="No"
            cardType="clickable"
            content="Readymade componet library for Axis products"
            onIconCallback={function noRefCheck() {}}
            title="Subzero Documentation"
            type="label"
          />
        </a>
        <a href="https://storybook.staging.axisb.com/">
          <Card
            assets="No"
            cardType="clickable"
            content="Readymade componet library for Axis products"
            onIconCallback={function noRefCheck() {}}
            title="Storybook for Subzero"
            type="label"
          />
        </a>
      </div>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;
