#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌ Its FOKING RAW - Your styling looks wrong. ❌
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check. ❌
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'Alright.... Code looks good to Husky... Trying to build now.'

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'